(function () {
  const BASE_URL = 'https://cdn.jsdelivr.net/npm/ionicons@6.1.2/dist/svg/';
  
  // كائن يحوي روابط جميع الأيقونات (400 أيقونة)
  const iconUrls = {
    // Basic Icons
    "add": BASE_URL + "add.svg",
    "add-circle": BASE_URL + "add-circle.svg",
    "airplane": BASE_URL + "airplane.svg",
    "alarm": BASE_URL + "alarm.svg",
    "albums": BASE_URL + "albums.svg",
    "alert": BASE_URL + "alert.svg",
    "alert-circle": BASE_URL + "alert-circle.svg",
    "american-football": BASE_URL + "american-football.svg",
    "analytics": BASE_URL + "analytics.svg",
    "aperture": BASE_URL + "aperture.svg",
    "apps": BASE_URL + "apps.svg",
    "archive": BASE_URL + "archive.svg",
    "arrow-back": BASE_URL + "arrow-back.svg",
    "arrow-back-circle": BASE_URL + "arrow-back-circle.svg",
    "arrow-down": BASE_URL + "arrow-down.svg",
    "arrow-down-circle": BASE_URL + "arrow-down-circle.svg",
    "arrow-forward": BASE_URL + "arrow-forward.svg",
    "arrow-forward-circle": BASE_URL + "arrow-forward-circle.svg",
    "arrow-redo": BASE_URL + "arrow-redo.svg",
    "arrow-redo-circle": BASE_URL + "arrow-redo-circle.svg",
    "arrow-undo": BASE_URL + "arrow-undo.svg",
    "arrow-undo-circle": BASE_URL + "arrow-undo-circle.svg",
    "arrow-up": BASE_URL + "arrow-up.svg",
    "arrow-up-circle": BASE_URL + "arrow-up-circle.svg",
    "at": BASE_URL + "at.svg",
    "at-circle": BASE_URL + "at-circle.svg",
    "attach": BASE_URL + "attach.svg",
    "backspace": BASE_URL + "backspace.svg",
    "bag": BASE_URL + "bag.svg",
    "bag-add": BASE_URL + "bag-add.svg",
    "bag-check": BASE_URL + "bag-check.svg",
    "bag-handle": BASE_URL + "bag-handle.svg",
    "bag-remove": BASE_URL + "bag-remove.svg",
    "balloon": BASE_URL + "balloon.svg",
    "ban": BASE_URL + "ban.svg",
    "bandage": BASE_URL + "bandage.svg",
    "bar-chart": BASE_URL + "bar-chart.svg",
    "barbell": BASE_URL + "barbell.svg",
    "barcode": BASE_URL + "barcode.svg",
    "baseball": BASE_URL + "baseball.svg",
    "basket": BASE_URL + "basket.svg",
    "basketball": BASE_URL + "basketball.svg",
    "battery-charging": BASE_URL + "battery-charging.svg",
    "battery-dead": BASE_URL + "battery-dead.svg",
    "battery-full": BASE_URL + "battery-full.svg",
    "battery-half": BASE_URL + "battery-half.svg",
    "beaker": BASE_URL + "beaker.svg",
    "bed": BASE_URL + "bed.svg",
    "beer": BASE_URL + "beer.svg",
    "bicycle": BASE_URL + "bicycle.svg",
    "bluetooth": BASE_URL + "bluetooth.svg",
    "boat": BASE_URL + "boat.svg",
    "body": BASE_URL + "body.svg",
    "bonfire": BASE_URL + "bonfire.svg",
    "book": BASE_URL + "book.svg",
    "bookmark": BASE_URL + "bookmark.svg",
    "bookmarks": BASE_URL + "bookmarks.svg",
    "bowling-ball": BASE_URL + "bowling-ball.svg",
    "briefcase": BASE_URL + "briefcase.svg",
    "browsers": BASE_URL + "browsers.svg",
    "brush": BASE_URL + "brush.svg",
    "bug": BASE_URL + "bug.svg",
    "build": BASE_URL + "build.svg",
    "bulb": BASE_URL + "bulb.svg",
    "bus": BASE_URL + "bus.svg",
    "business": BASE_URL + "business.svg",
    "cafe": BASE_URL + "cafe.svg",
    "calculator": BASE_URL + "calculator.svg",
    "calendar": BASE_URL + "calendar.svg",
    "calendar-clear": BASE_URL + "calendar-clear.svg",
    "calendar-number": BASE_URL + "calendar-number.svg",
    "call": BASE_URL + "call.svg",
    "camera": BASE_URL + "camera.svg",
    "camera-reverse": BASE_URL + "camera-reverse.svg",
    "car": BASE_URL + "car.svg",
    "car-sport": BASE_URL + "car-sport.svg",
    "card": BASE_URL + "card.svg",
    "caret-back": BASE_URL + "caret-back.svg",
    "caret-back-circle": BASE_URL + "caret-back-circle.svg",
    "caret-down": BASE_URL + "caret-down.svg",
    "caret-down-circle": BASE_URL + "caret-down-circle.svg",
    "caret-forward": BASE_URL + "caret-forward.svg",
    "caret-forward-circle": BASE_URL + "caret-forward-circle.svg",
    "caret-up": BASE_URL + "caret-up.svg",
    "caret-up-circle": BASE_URL + "caret-up-circle.svg",
    "cart": BASE_URL + "cart.svg",
    "cash": BASE_URL + "cash.svg",
    "cellular": BASE_URL + "cellular.svg",
    "chatbox": BASE_URL + "chatbox.svg",
    "chatbox-ellipses": BASE_URL + "chatbox-ellipses.svg",
    "chatbubble": BASE_URL + "chatbubble.svg",
    "chatbubble-ellipses": BASE_URL + "chatbubble-ellipses.svg",
    "chatbubbles": BASE_URL + "chatbubbles.svg",
    "checkbox": BASE_URL + "checkbox.svg",
    "checkmark": BASE_URL + "checkmark.svg",
    "checkmark-circle": BASE_URL + "checkmark-circle.svg",
    "checkmark-done": BASE_URL + "checkmark-done.svg",
    "checkmark-done-circle": BASE_URL + "checkmark-done-circle.svg",
    "chevron-back": BASE_URL + "chevron-back.svg",
    "chevron-back-circle": BASE_URL + "chevron-back-circle.svg",
    "chevron-down": BASE_URL + "chevron-down.svg",
    "chevron-down-circle": BASE_URL + "chevron-down-circle.svg",
    "chevron-forward": BASE_URL + "chevron-forward.svg",
    "chevron-forward-circle": BASE_URL + "chevron-forward-circle.svg",
    "chevron-up": BASE_URL + "chevron-up.svg",
    "chevron-up-circle": BASE_URL + "chevron-up-circle.svg",
    "clipboard": BASE_URL + "clipboard.svg",
    "close": BASE_URL + "close.svg",
    "close-circle": BASE_URL + "close-circle.svg",
    "cloud": BASE_URL + "cloud.svg",
    "cloud-circle": BASE_URL + "cloud-circle.svg",
    "cloud-done": BASE_URL + "cloud-done.svg",
    "cloud-download": BASE_URL + "cloud-download.svg",
    "cloud-offline": BASE_URL + "cloud-offline.svg",
    "cloud-upload": BASE_URL + "cloud-upload.svg",
    "cloudy": BASE_URL + "cloudy.svg",
    "cloudy-night": BASE_URL + "cloudy-night.svg",
    "code": BASE_URL + "code.svg",
    "code-download": BASE_URL + "code-download.svg",
    "code-slash": BASE_URL + "code-slash.svg",
    "code-working": BASE_URL + "code-working.svg",
    "cog": BASE_URL + "cog.svg",
    "color-fill": BASE_URL + "color-fill.svg",
    "color-filter": BASE_URL + "color-filter.svg",
    "color-palette": BASE_URL + "color-palette.svg",
    "color-wand": BASE_URL + "color-wand.svg",
    "compass": BASE_URL + "compass.svg",
    "construct": BASE_URL + "construct.svg",
    "contract": BASE_URL + "contract.svg",
    "contrast": BASE_URL + "contrast.svg",
    "copy": BASE_URL + "copy.svg",
    "create": BASE_URL + "create.svg",
    "crop": BASE_URL + "crop.svg",
    "cube": BASE_URL + "cube.svg",
    "cut": BASE_URL + "cut.svg",
    "desktop": BASE_URL + "desktop.svg",
    "diamond": BASE_URL + "diamond.svg",
    "dice": BASE_URL + "dice.svg",
    "disc": BASE_URL + "disc.svg",
    "document": BASE_URL + "document.svg",
    "document-attach": BASE_URL + "document-attach.svg",
    "document-text": BASE_URL + "document-text.svg",
    "documents": BASE_URL + "documents.svg",
    "download": BASE_URL + "download.svg",
    "duplicate": BASE_URL + "duplicate.svg",
    "ear": BASE_URL + "ear.svg",
    "earth": BASE_URL + "earth.svg",
    "easel": BASE_URL + "easel.svg",
    "egg": BASE_URL + "egg.svg",
    "ellipse": BASE_URL + "ellipse.svg",
    "ellipsis-horizontal": BASE_URL + "ellipsis-horizontal.svg",
    "ellipsis-horizontal-circle": BASE_URL + "ellipsis-horizontal-circle.svg",
    "ellipsis-vertical": BASE_URL + "ellipsis-vertical.svg",
    "ellipsis-vertical-circle": BASE_URL + "ellipsis-vertical-circle.svg",
    "enter": BASE_URL + "enter.svg",
    "exit": BASE_URL + "exit.svg",
    "expand": BASE_URL + "expand.svg",
    "extension-puzzle": BASE_URL + "extension-puzzle.svg",
    "eye": BASE_URL + "eye.svg",
    "eye-off": BASE_URL + "eye-off.svg",
    "eyedrop": BASE_URL + "eyedrop.svg",
    "fast-food": BASE_URL + "fast-food.svg",
    "female": BASE_URL + "female.svg",
    "file-tray": BASE_URL + "file-tray.svg",
    "file-tray-full": BASE_URL + "file-tray-full.svg",
    "file-tray-stacked": BASE_URL + "file-tray-stacked.svg",
    "film": BASE_URL + "film.svg",
    "filter": BASE_URL + "filter.svg",
    "filter-circle": BASE_URL + "filter-circle.svg",
    "finger-print": BASE_URL + "finger-print.svg",
    "fish": BASE_URL + "fish.svg",
    "fitness": BASE_URL + "fitness.svg",
    "flag": BASE_URL + "flag.svg",
    "flame": BASE_URL + "flame.svg",
    "flash": BASE_URL + "flash.svg",
    "flash-off": BASE_URL + "flash-off.svg",
    "flashlight": BASE_URL + "flashlight.svg",
    "flask": BASE_URL + "flask.svg",
    "flower": BASE_URL + "flower.svg",
    "folder": BASE_URL + "folder.svg",
    "folder-open": BASE_URL + "folder-open.svg",
    "football": BASE_URL + "football.svg",
    "footsteps": BASE_URL + "footsteps.svg",
    "funnel": BASE_URL + "funnel.svg",
    "game-controller": BASE_URL + "game-controller.svg",
    "gift": BASE_URL + "gift.svg",
    "git-branch": BASE_URL + "git-branch.svg",
    "git-commit": BASE_URL + "git-commit.svg",
    "git-compare": BASE_URL + "git-compare.svg",
    "git-merge": BASE_URL + "git-merge.svg",
    "git-network": BASE_URL + "git-network.svg",
    "git-pull-request": BASE_URL + "git-pull-request.svg",
    "glasses": BASE_URL + "glasses.svg",
    "globe": BASE_URL + "globe.svg",
    "golf": BASE_URL + "golf.svg",
    "grid": BASE_URL + "grid.svg",
    "hammer": BASE_URL + "hammer.svg",
    "hand-left": BASE_URL + "hand-left.svg",
    "hand-right": BASE_URL + "hand-right.svg",
    "happy": BASE_URL + "happy.svg",
    "hardware-chip": BASE_URL + "hardware-chip.svg",
    "headset": BASE_URL + "headset.svg",
    "heart": BASE_URL + "heart.svg",
    "heart-circle": BASE_URL + "heart-circle.svg",
    "heart-dislike": BASE_URL + "heart-dislike.svg",
    "heart-dislike-circle": BASE_URL + "heart-dislike-circle.svg",
    "heart-half": BASE_URL + "heart-half.svg",
    "help": BASE_URL + "help.svg",
    "help-buoy": BASE_URL + "help-buoy.svg",
    "help-circle": BASE_URL + "help-circle.svg",
    "home": BASE_URL + "home.svg",
    "hourglass": BASE_URL + "hourglass.svg",
    "ice-cream": BASE_URL + "ice-cream.svg",
    "id-card": BASE_URL + "id-card.svg",
    "image": BASE_URL + "image.svg",
    "images": BASE_URL + "images.svg",
    "infinite": BASE_URL + "infinite.svg",
    "information": BASE_URL + "information.svg",
    "information-circle": BASE_URL + "information-circle.svg",
    "invert-mode": BASE_URL + "invert-mode.svg",
    "journal": BASE_URL + "journal.svg",
    "key": BASE_URL + "key.svg",
    "keypad": BASE_URL + "keypad.svg",
    "language": BASE_URL + "language.svg",
    "laptop": BASE_URL + "laptop.svg",
    "layers": BASE_URL + "layers.svg",
    "leaf": BASE_URL + "leaf.svg",
    "library": BASE_URL + "library.svg",
    "link": BASE_URL + "link.svg",
    "list": BASE_URL + "list.svg",
    "list-circle": BASE_URL + "list-circle.svg",
    "locate": BASE_URL + "locate.svg",
    "location": BASE_URL + "location.svg",
    "lock-closed": BASE_URL + "lock-closed.svg",
    "lock-open": BASE_URL + "lock-open.svg",
    "log-in": BASE_URL + "log-in.svg",
    "log-out": BASE_URL + "log-out.svg",
    "logo-alipay": BASE_URL + "logo-alipay.svg",
    "logo-amazon": BASE_URL + "logo-amazon.svg",
    "logo-amplify": BASE_URL + "logo-amplify.svg",
    "logo-android": BASE_URL + "logo-android.svg",
    "logo-angular": BASE_URL + "logo-angular.svg",
    "logo-apple": BASE_URL + "logo-apple.svg",
    "logo-apple-appstore": BASE_URL + "logo-apple-appstore.svg",
    "logo-apple-ar": BASE_URL + "logo-apple-ar.svg",
    "logo-behance": BASE_URL + "logo-behance.svg",
    "logo-bitbucket": BASE_URL + "logo-bitbucket.svg",
    "logo-bitcoin": BASE_URL + "logo-bitcoin.svg",
    "logo-buffer": BASE_URL + "logo-buffer.svg",
    "logo-capacitor": BASE_URL + "logo-capacitor.svg",
    "logo-chrome": BASE_URL + "logo-chrome.svg",
    "logo-closed-captioning": BASE_URL + "logo-closed-captioning.svg",
    "logo-codepen": BASE_URL + "logo-codepen.svg",
    "logo-css3": BASE_URL + "logo-css3.svg",
    "logo-designernews": BASE_URL + "logo-designernews.svg",
    "logo-deviantart": BASE_URL + "logo-deviantart.svg",
    "logo-discord": BASE_URL + "logo-discord.svg",
    "logo-docker": BASE_URL + "logo-docker.svg",
    "logo-dribbble": BASE_URL + "logo-dribbble.svg",
    "logo-dropbox": BASE_URL + "logo-dropbox.svg",
    "logo-edge": BASE_URL + "logo-edge.svg",
    "logo-electron": BASE_URL + "logo-electron.svg",
    "logo-euro": BASE_URL + "logo-euro.svg",
    "logo-facebook": BASE_URL + "logo-facebook.svg",
    "logo-figma": BASE_URL + "logo-figma.svg",
    "logo-firebase": BASE_URL + "logo-firebase.svg",
    "logo-firefox": BASE_URL + "logo-firefox.svg",
    "logo-flickr": BASE_URL + "logo-flickr.svg",
    "logo-foursquare": BASE_URL + "logo-foursquare.svg",
    "logo-github": BASE_URL + "logo-github.svg",
    "logo-gitlab": BASE_URL + "logo-gitlab.svg",
    "logo-google": BASE_URL + "logo-google.svg",
    "logo-google-playstore": BASE_URL + "logo-google-playstore.svg",
    "logo-hackernews": BASE_URL + "logo-hackernews.svg",
    "logo-html5": BASE_URL + "logo-html5.svg",
    "logo-instagram": BASE_URL + "logo-instagram.svg",
    "logo-ionic": BASE_URL + "logo-ionic.svg",
    "logo-ionitron": BASE_URL + "logo-ionitron.svg",
    "logo-javascript": BASE_URL + "logo-javascript.svg",
    "logo-laravel": BASE_URL + "logo-laravel.svg",
    "logo-linkedin": BASE_URL + "logo-linkedin.svg",
    "logo-markdown": BASE_URL + "logo-markdown.svg",
    "logo-mastodon": BASE_URL + "logo-mastodon.svg",
    "logo-medium": BASE_URL + "logo-medium.svg",
    "logo-microsoft": BASE_URL + "logo-microsoft.svg",
    "logo-nodejs": BASE_URL + "logo-nodejs.svg",
    "logo-no-smoking": BASE_URL + "logo-no-smoking.svg",
    "logo-npm": BASE_URL + "logo-npm.svg",
    "logo-octocat": BASE_URL + "logo-octocat.svg",
    "logo-paypal": BASE_URL + "logo-paypal.svg",
    "logo-pinterest": BASE_URL + "logo-pinterest.svg",
    "logo-playstation": BASE_URL + "logo-playstation.svg",
    "logo-product-hunt": BASE_URL + "logo-product-hunt.svg",
    "logo-pwa": BASE_URL + "logo-pwa.svg",
    "logo-python": BASE_URL + "logo-python.svg",
    "logo-react": BASE_URL + "logo-react.svg",
    "logo-reddit": BASE_URL + "logo-reddit.svg",
    "logo-rss": BASE_URL + "logo-rss.svg",
    "logo-sass": BASE_URL + "logo-sass.svg",
    "logo-skype": BASE_URL + "logo-skype.svg",
    "logo-slack": BASE_URL + "logo-slack.svg",
    "logo-snapchat": BASE_URL + "logo-snapchat.svg",
    "logo-soundcloud": BASE_URL + "logo-soundcloud.svg",
    "logo-stackoverflow": BASE_URL + "logo-stackoverflow.svg",
    "logo-steam": BASE_URL + "logo-steam.svg",
    "logo-stencil": BASE_URL + "logo-stencil.svg",
    "logo-tableau": BASE_URL + "logo-tableau.svg",
    "logo-tiktok": BASE_URL + "logo-tiktok.svg",
    "logo-tumblr": BASE_URL + "logo-tumblr.svg",
    "logo-tux": BASE_URL + "logo-tux.svg",
    "logo-twitch": BASE_URL + "logo-twitch.svg",
    "logo-twitter": BASE_URL + "logo-twitter.svg",
    "logo-usd": BASE_URL + "logo-usd.svg",
    "logo-venmo": BASE_URL + "logo-venmo.svg",
    "logo-vercel": BASE_URL + "logo-vercel.svg",
    "logo-vimeo": BASE_URL + "logo-vimeo.svg",
    "logo-vk": BASE_URL + "logo-vk.svg",
    "logo-vue": BASE_URL + "logo-vue.svg",
    "logo-web-component": BASE_URL + "logo-web-component.svg",
    "logo-wechat": BASE_URL + "logo-wechat.svg",
    "logo-whatsapp": BASE_URL + "logo-whatsapp.svg",
    "logo-windows": BASE_URL + "logo-windows.svg",
    "logo-wordpress": BASE_URL + "logo-wordpress.svg",
    "logo-xbox": BASE_URL + "logo-xbox.svg",
    "logo-xing": BASE_URL + "logo-xing.svg",
    "logo-yahoo": BASE_URL + "logo-yahoo.svg",
    "logo-yen": BASE_URL + "logo-yen.svg",
    "logo-youtube": BASE_URL + "logo-youtube.svg",
    "magnet": BASE_URL + "magnet.svg",
    "mail": BASE_URL + "mail.svg",
    "mail-open": BASE_URL + "mail-open.svg",
    "mail-unread": BASE_URL + "mail-unread.svg",
    "male": BASE_URL + "male.svg",
    "male-female": BASE_URL + "male-female.svg",
    "man": BASE_URL + "man.svg",
    "map": BASE_URL + "map.svg",
    "medal": BASE_URL + "medal.svg",
    "medical": BASE_URL + "medical.svg",
    "medkit": BASE_URL + "medkit.svg",
    "megaphone": BASE_URL + "megaphone.svg",
    "menu": BASE_URL + "menu.svg",
    "mic": BASE_URL + "mic.svg",
    "mic-circle": BASE_URL + "mic-circle.svg",
    "mic-off": BASE_URL + "mic-off.svg",
    "mic-off-circle": BASE_URL + "mic-off-circle.svg",
    "moon": BASE_URL + "moon.svg",
    "move": BASE_URL + "move.svg",
    "musical-note": BASE_URL + "musical-note.svg",
    "musical-notes": BASE_URL + "musical-notes.svg",
    "navigate": BASE_URL + "navigate.svg",
    "navigate-circle": BASE_URL + "navigate-circle.svg",
    "newspaper": BASE_URL + "newspaper.svg",
    "notifications": BASE_URL + "notifications.svg",
    "notifications-circle": BASE_URL + "notifications-circle.svg",
    "notifications-off": BASE_URL + "notifications-off.svg",
    "notifications-off-circle": BASE_URL + "notifications-off-circle.svg",
    "nuclear": BASE_URL + "nuclear.svg",
    "nutrition": BASE_URL + "nutrition.svg",
    "open": BASE_URL + "open.svg",
    "options": BASE_URL + "options.svg",
    "paper-plane": BASE_URL + "paper-plane.svg",
    "partly-sunny": BASE_URL + "partly-sunny.svg",
    "pause": BASE_URL + "pause.svg",
    "pause-circle": BASE_URL + "pause-circle.svg",
    "paw": BASE_URL + "paw.svg",
    "pencil": BASE_URL + "pencil.svg",
    "people": BASE_URL + "people.svg",
    "people-circle": BASE_URL + "people-circle.svg",
    "person": BASE_URL + "person.svg",
    "person-add": BASE_URL + "person-add.svg",
    "person-circle": BASE_URL + "person-circle.svg",
    "person-remove": BASE_URL + "person-remove.svg",
    "phone-landscape": BASE_URL + "phone-landscape.svg",
    "phone-portrait": BASE_URL + "phone-portrait.svg",
    "pie-chart": BASE_URL + "pie-chart.svg",
    "pin": BASE_URL + "pin.svg",
    "pint": BASE_URL + "pint.svg",
    "pizza": BASE_URL + "pizza.svg",
    "planet": BASE_URL + "planet.svg",
    "play": BASE_URL + "play.svg",
    "play-back": BASE_URL + "play-back.svg",
    "play-back-circle": BASE_URL + "play-back-circle.svg",
    "play-circle": BASE_URL + "play-circle.svg",
    "play-forward": BASE_URL + "play-forward.svg",
    "play-forward-circle": BASE_URL + "play-forward-circle.svg",
    "play-skip-back": BASE_URL + "play-skip-back.svg",
    "play-skip-back-circle": BASE_URL + "play-skip-back-circle.svg",
    "play-skip-forward": BASE_URL + "play-skip-forward.svg",
    "play-skip-forward-circle": BASE_URL + "play-skip-forward-circle.svg",
    "podium": BASE_URL + "podium.svg",
    "power": BASE_URL + "power.svg",
    "pricetag": BASE_URL + "pricetag.svg",
    "pricetags": BASE_URL + "pricetags.svg",
    "print": BASE_URL + "print.svg",
    "prism": BASE_URL + "prism.svg",
    "pulse": BASE_URL + "pulse.svg",
    "push": BASE_URL + "push.svg",
    "qr-code": BASE_URL + "qr-code.svg",
    "radio": BASE_URL + "radio.svg",
    "radio-button-off": BASE_URL + "radio-button-off.svg",
    "radio-button-on": BASE_URL + "radio-button-on.svg",
    "rainy": BASE_URL + "rainy.svg",
    "reader": BASE_URL + "reader.svg",
    "receipt": BASE_URL + "receipt.svg",
    "recording": BASE_URL + "recording.svg",
    "refresh": BASE_URL + "refresh.svg",
    "refresh-circle": BASE_URL + "refresh-circle.svg",
    "reload": BASE_URL + "reload.svg",
    "reload-circle": BASE_URL + "reload-circle.svg",
    "remove": BASE_URL + "remove.svg",
    "remove-circle": BASE_URL + "remove-circle.svg",
    "reorder-four": BASE_URL + "reorder-four.svg",
    "reorder-three": BASE_URL + "reorder-three.svg",
    "reorder-two": BASE_URL + "reorder-two.svg",
    "repeat": BASE_URL + "repeat.svg",
    "resize": BASE_URL + "resize.svg",
    "restaurant": BASE_URL + "restaurant.svg",
    "return-down-back": BASE_URL + "return-down-back.svg",
    "return-down-forward": BASE_URL + "return-down-forward.svg",
    "return-up-back": BASE_URL + "return-up-back.svg",
    "return-up-forward": BASE_URL + "return-up-forward.svg",
    "ribbon": BASE_URL + "ribbon.svg",
    "rocket": BASE_URL + "rocket.svg",
    "rose": BASE_URL + "rose.svg",
    "sad": BASE_URL + "sad.svg",
    "save": BASE_URL + "save.svg",
    "scan": BASE_URL + "scan.svg",
    "scan-circle": BASE_URL + "scan-circle.svg",
    "school": BASE_URL + "school.svg",
    "search": BASE_URL + "search.svg",
    "search-circle": BASE_URL + "search-circle.svg",
    "send": BASE_URL + "send.svg",
    "server": BASE_URL + "server.svg",
    "settings": BASE_URL + "settings.svg",
    "shapes": BASE_URL + "shapes.svg",
    "share": BASE_URL + "share.svg",
    "share-social": BASE_URL + "share-social.svg",
    "shield": BASE_URL + "shield.svg",
    "shield-checkmark": BASE_URL + "shield-checkmark.svg",
    "shield-half": BASE_URL + "shield-half.svg",
    "shirt": BASE_URL + "shirt.svg",
    "shuffle": BASE_URL + "shuffle.svg",
    "skull": BASE_URL + "skull.svg",
    "snow": BASE_URL + "snow.svg",
    "sparkles": BASE_URL + "sparkles.svg",
    "speedometer": BASE_URL + "speedometer.svg",
    "square": BASE_URL + "square.svg",
    "star": BASE_URL + "star.svg",
    "star-half": BASE_URL + "star-half.svg",
    "stats-chart": BASE_URL + "stats-chart.svg",
    "stop": BASE_URL + "stop.svg",
    "stop-circle": BASE_URL + "stop-circle.svg",
    "stopwatch": BASE_URL + "stopwatch.svg",
    "storefront": BASE_URL + "storefront.svg",
    "subway": BASE_URL + "subway.svg",
    "sunny": BASE_URL + "sunny.svg",
    "swap-horizontal": BASE_URL + "swap-horizontal.svg",
    "swap-vertical": BASE_URL + "swap-vertical.svg",
    "sync": BASE_URL + "sync.svg",
    "sync-circle": BASE_URL + "sync-circle.svg",
    "tablet-landscape": BASE_URL + "tablet-landscape.svg",
    "tablet-portrait": BASE_URL + "tablet-portrait.svg",
    "telescope": BASE_URL + "telescope.svg",
    "tennisball": BASE_URL + "tennisball.svg",
    "terminal": BASE_URL + "terminal.svg",
    "text": BASE_URL + "text.svg",
    "thermometer": BASE_URL + "thermometer.svg",
    "thumbs-down": BASE_URL + "thumbs-down.svg",
    "thumbs-up": BASE_URL + "thumbs-up.svg",
    "thunderstorm": BASE_URL + "thunderstorm.svg",
    "time": BASE_URL + "time.svg",
    "timer": BASE_URL + "timer.svg",
    "today": BASE_URL + "today.svg",
    "toggle": BASE_URL + "toggle.svg",
    "trail-sign": BASE_URL + "trail-sign.svg",
    "train": BASE_URL + "train.svg",
    "transgender": BASE_URL + "transgender.svg",
    "trash": BASE_URL + "trash.svg",
    "trash-bin": BASE_URL + "trash-bin.svg",
    "trending-down": BASE_URL + "trending-down.svg",
    "trending-up": BASE_URL + "trending-up.svg",
    "triangle": BASE_URL + "triangle.svg",
    "trophy": BASE_URL + "trophy.svg",
    "tv": BASE_URL + "tv.svg",
    "umbrella": BASE_URL + "umbrella.svg",
    "unlink": BASE_URL + "unlink.svg",
    "videocam": BASE_URL + "videocam.svg",
    "videocam-off": BASE_URL + "videocam-off.svg",
    "volume-high": BASE_URL + "volume-high.svg",
    "volume-low": BASE_URL + "volume-low.svg",
    "volume-medium": BASE_URL + "volume-medium.svg",
    "volume-mute": BASE_URL + "volume-mute.svg",
    "volume-off": BASE_URL + "volume-off.svg",
    "walk": BASE_URL + "walk.svg",
    "wallet": BASE_URL + "wallet.svg",
    "warning": BASE_URL + "warning.svg",
    "watch": BASE_URL + "watch.svg",
    "water": BASE_URL + "water.svg",
    "wifi": BASE_URL + "wifi.svg",
    "wine": BASE_URL + "wine.svg",
    "woman": BASE_URL + "woman.svg"
  };

 
  // كائن لتخزين مسارات SVG بعد جلبها
  const iconPaths = {};

  async function fetchIconPath(url) {
    try {
      const response = await fetch(url);
      const svgText = await response.text();
      const parser = new DOMParser();
      const svgDoc = parser.parseFromString(svgText, 'image/svg+xml');
      return svgDoc.querySelector('path').getAttribute('d');
    } catch (error) {
      console.error('Failed to fetch icon:', error);
      return '';
    }
  }

  async function injectIcons() {
    const elements = document.querySelectorAll('[data-canyon-icon]');
    
    for (const el of elements) {
      const iconName = el.getAttribute('data-canyon-icon').trim().toLowerCase();
      const iconUrl = iconUrls[iconName];
      
      if (iconUrl) {
        // إذا لم يتم جلب المسار بعد، قم بجلبها وتخزينها
        if (!iconPaths[iconName]) {
          iconPaths[iconName] = await fetchIconPath(iconUrl);
        }

        // إنشاء عنصر SVG
        const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
        svg.setAttribute('viewBox', '0 0 512 512');
        svg.setAttribute('fill', 'currentColor');
        svg.setAttribute('aria-hidden', 'true');
        svg.style.width = '100%';
        svg.style.height = '100%';
        
        // إنشاء عنصر Path
        const path = document.createElementNS('http://www.w3.org/2000/svg', 'path');
        path.setAttribute('d', iconPaths[iconName]);
        
        // مسح المحتوى الحالي
        while (el.firstChild) {
          el.removeChild(el.firstChild);
        }
        
        // إضافة العناصر
        svg.appendChild(path);
        el.appendChild(svg);
        
        // تخزين رابط الصورة الأصلي كخاصية بيانات
        el.dataset.iconUrl = iconUrl;
      }
    }
  }

  // التنفيذ عند تحميل الصفحة
  if (document.readyState !== 'loading') {
    injectIcons();
  } else {
    document.addEventListener('DOMContentLoaded', injectIcons);
  }

  // واجهة البرمجة
  window.CanyonIcons = {
    inject: injectIcons,
    list: () => Object.keys(iconUrls),
    addIcon: (name, url) => { 
      iconUrls[name] = url;
      // عند إضافة أيقونة جديدة، يجب جلب مسارها عند الحاجة
      delete iconPaths[name];
    },
    getIconUrl: (name) => iconUrls[name],
    getIconPath: async (name) => {
      if (!iconPaths[name] && iconUrls[name]) {
        iconPaths[name] = await fetchIconPath(iconUrls[name]);
      }
      return iconPaths[name];
    }
  };
})();
