(function () {
  const iconImages = {
    // Basic Icons
    "add": "https://ionic.io/ionicons/svg/add.svg",
    "add-circle": "https://ionic.io/ionicons/svg/add-circle.svg",
    "airplane": "https://ionic.io/ionicons/svg/airplane.svg",
    "alarm": "https://ionic.io/ionicons/svg/alarm.svg",
    "albums": "https://ionic.io/ionicons/svg/albums.svg",
    "alert": "https://ionic.io/ionicons/svg/alert.svg",
    "alert-circle": "https://ionic.io/ionicons/svg/alert-circle.svg",
    "american-football": "https://ionic.io/ionicons/svg/american-football.svg",
    "analytics": "https://ionic.io/ionicons/svg/analytics.svg",
    "aperture": "https://ionic.io/ionicons/svg/aperture.svg",
    "apps": "https://ionic.io/ionicons/svg/apps.svg",
    "archive": "https://ionic.io/ionicons/svg/archive.svg",
    "arrow-back": "https://ionic.io/ionicons/svg/arrow-back.svg",
    "arrow-down": "https://ionic.io/ionicons/svg/arrow-down.svg",
    "arrow-forward": "https://ionic.io/ionicons/svg/arrow-forward.svg",
    "arrow-redo": "https://ionic.io/ionicons/svg/arrow-redo.svg",
    "arrow-undo": "https://ionic.io/ionicons/svg/arrow-undo.svg",
    "arrow-up": "https://ionic.io/ionicons/svg/arrow-up.svg",
    "at": "https://ionic.io/ionicons/svg/at.svg",
    "at-circle": "https://ionic.io/ionicons/svg/at-circle.svg",
    "attach": "https://ionic.io/ionicons/svg/attach.svg",
    "backspace": "https://ionic.io/ionicons/svg/backspace.svg",
    "bag": "https://ionic.io/ionicons/svg/bag.svg",
    "bag-add": "https://ionic.io/ionicons/svg/bag-add.svg",
    "bag-check": "https://ionic.io/ionicons/svg/bag-check.svg",
    "bag-handle": "https://ionic.io/ionicons/svg/bag-handle.svg",
    "bag-remove": "https://ionic.io/ionicons/svg/bag-remove.svg",
    "balloon": "https://ionic.io/ionicons/svg/balloon.svg",
    "ban": "https://ionic.io/ionicons/svg/ban.svg",
    "bandage": "https://ionic.io/ionicons/svg/bandage.svg",
    "bar-chart": "https://ionic.io/ionicons/svg/bar-chart.svg",
    "barbell": "https://ionic.io/ionicons/svg/barbell.svg",
    "barcode": "https://ionic.io/ionicons/svg/barcode.svg",
    "baseball": "https://ionic.io/ionicons/svg/baseball.svg",
    "basket": "https://ionic.io/ionicons/svg/basket.svg",
    "basketball": "https://ionic.io/ionicons/svg/basketball.svg",
    "battery-charging": "https://ionic.io/ionicons/svg/battery-charging.svg",
    "battery-dead": "https://ionic.io/ionicons/svg/battery-dead.svg",
    "battery-full": "https://ionic.io/ionicons/svg/battery-full.svg",
    "battery-half": "https://ionic.io/ionicons/svg/battery-half.svg",
    "beaker": "https://ionic.io/ionicons/svg/beaker.svg",
    "bed": "https://ionic.io/ionicons/svg/bed.svg",
    "beer": "https://ionic.io/ionicons/svg/beer.svg",
    "bicycle": "https://ionic.io/ionicons/svg/bicycle.svg",
    "bluetooth": "https://ionic.io/ionicons/svg/bluetooth.svg",
    "boat": "https://ionic.io/ionicons/svg/boat.svg",
    "body": "https://ionic.io/ionicons/svg/body.svg",
    "bonfire": "https://ionic.io/ionicons/svg/bonfire.svg",
    "book": "https://ionic.io/ionicons/svg/book.svg",
    "bookmark": "https://ionic.io/ionicons/svg/bookmark.svg",
    "bookmarks": "https://ionic.io/ionicons/svg/bookmarks.svg",
    "bowling-ball": "https://ionic.io/ionicons/svg/bowling-ball.svg",
    "briefcase": "https://ionic.io/ionicons/svg/briefcase.svg",
    "browsers": "https://ionic.io/ionicons/svg/browsers.svg",
    "brush": "https://ionic.io/ionicons/svg/brush.svg",
    "bug": "https://ionic.io/ionicons/svg/bug.svg",
    "build": "https://ionic.io/ionicons/svg/build.svg",
    "bulb": "https://ionic.io/ionicons/svg/bulb.svg",
    "bus": "https://ionic.io/ionicons/svg/bus.svg",
    "business": "https://ionic.io/ionicons/svg/business.svg",
    "cafe": "https://ionic.io/ionicons/svg/cafe.svg",
    "calculator": "https://ionic.io/ionicons/svg/calculator.svg",
    "calendar": "https://ionic.io/ionicons/svg/calendar.svg",
    "calendar-clear": "https://ionic.io/ionicons/svg/calendar-clear.svg",
    "calendar-number": "https://ionic.io/ionicons/svg/calendar-number.svg",
    "call": "https://ionic.io/ionicons/svg/call.svg",
    "camera": "https://ionic.io/ionicons/svg/camera.svg",
    "camera-reverse": "https://ionic.io/ionicons/svg/camera-reverse.svg",
    "car": "https://ionic.io/ionicons/svg/car.svg",
    "car-sport": "https://ionic.io/ionicons/svg/car-sport.svg",
    "card": "https://ionic.io/ionicons/svg/card.svg",
    "caret-back": "https://ionic.io/ionicons/svg/caret-back.svg",
    "caret-down": "https://ionic.io/ionicons/svg/caret-down.svg",
    "caret-forward": "https://ionic.io/ionicons/svg/caret-forward.svg",
    "caret-up": "https://ionic.io/ionicons/svg/caret-up.svg",
    "cart": "https://ionic.io/ionicons/svg/cart.svg",
    "cash": "https://ionic.io/ionicons/svg/cash.svg",
    "cellular": "https://ionic.io/ionicons/svg/cellular.svg",
    "chatbox": "https://ionic.io/ionicons/svg/chatbox.svg",
    "chatbox-ellipses": "https://ionic.io/ionicons/svg/chatbox-ellipses.svg",
    "chatbubble": "https://ionic.io/ionicons/svg/chatbubble.svg",
    "chatbubble-ellipses": "https://ionic.io/ionicons/svg/chatbubble-ellipses.svg",
    "chatbubbles": "https://ionic.io/ionicons/svg/chatbubbles.svg",
    "checkbox": "https://ionic.io/ionicons/svg/checkbox.svg",
    "checkbox-outline": "https://ionic.io/ionicons/svg/checkbox-outline.svg",
    "checkmark": "https://ionic.io/ionicons/svg/checkmark.svg",
    "checkmark-circle": "https://ionic.io/ionicons/svg/checkmark-circle.svg",
    "checkmark-done": "https://ionic.io/ionicons/svg/checkmark-done.svg",
    "checkmark-done-circle": "https://ionic.io/ionicons/svg/checkmark-done-circle.svg",
    "chevron-back": "https://ionic.io/ionicons/svg/chevron-back.svg",
    "chevron-down": "https://ionic.io/ionicons/svg/chevron-down.svg",
    "chevron-forward": "https://ionic.io/ionicons/svg/chevron-forward.svg",
    "chevron-up": "https://ionic.io/ionicons/svg/chevron-up.svg",
    "clipboard": "https://ionic.io/ionicons/svg/clipboard.svg",
    "close": "https://ionic.io/ionicons/svg/close.svg",
    "close-circle": "https://ionic.io/ionicons/svg/close-circle.svg",
    "cloud": "https://ionic.io/ionicons/svg/cloud.svg",
    "cloud-circle": "https://ionic.io/ionicons/svg/cloud-circle.svg",
    "cloud-done": "https://ionic.io/ionicons/svg/cloud-done.svg",
    "cloud-download": "https://ionic.io/ionicons/svg/cloud-download.svg",
    "cloud-offline": "https://ionic.io/ionicons/svg/cloud-offline.svg",
    "cloud-upload": "https://ionic.io/ionicons/svg/cloud-upload.svg",
    "cloudy": "https://ionic.io/ionicons/svg/cloudy.svg",
    "cloudy-night": "https://ionic.io/ionicons/svg/cloudy-night.svg",
    "code": "https://ionic.io/ionicons/svg/code.svg",
    "code-download": "https://ionic.io/ionicons/svg/code-download.svg",
    "code-slash": "https://ionic.io/ionicons/svg/code-slash.svg",
    "code-working": "https://ionic.io/ionicons/svg/code-working.svg",
    "cog": "https://ionic.io/ionicons/svg/cog.svg",
    "color-fill": "https://ionic.io/ionicons/svg/color-fill.svg",
    "color-filter": "https://ionic.io/ionicons/svg/color-filter.svg",
    "color-palette": "https://ionic.io/ionicons/svg/color-palette.svg",
    "color-wand": "https://ionic.io/ionicons/svg/color-wand.svg",
    "compass": "https://ionic.io/ionicons/svg/compass.svg",
    "construct": "https://ionic.io/ionicons/svg/construct.svg",
    "contract": "https://ionic.io/ionicons/svg/contract.svg",
    "contrast": "https://ionic.io/ionicons/svg/contrast.svg",
    "copy": "https://ionic.io/ionicons/svg/copy.svg",
    "create": "https://ionic.io/ionicons/svg/create.svg",
    "crop": "https://ionic.io/ionicons/svg/crop.svg",
    "cube": "https://ionic.io/ionicons/svg/cube.svg",
    "cut": "https://ionic.io/ionicons/svg/cut.svg",
    "desktop": "https://ionic.io/ionicons/svg/desktop.svg",
    "diamond": "https://ionic.io/ionicons/svg/diamond.svg",
    "dice": "https://ionic.io/ionicons/svg/dice.svg",
    "disc": "https://ionic.io/ionicons/svg/disc.svg",
    "document": "https://ionic.io/ionicons/svg/document.svg",
    "document-attach": "https://ionic.io/ionicons/svg/document-attach.svg",
    "document-lock": "https://ionic.io/ionicons/svg/document-lock.svg",
    "document-text": "https://ionic.io/ionicons/svg/document-text.svg",
    "documents": "https://ionic.io/ionicons/svg/documents.svg",
    "download": "https://ionic.io/ionicons/svg/download.svg",
    "duplicate": "https://ionic.io/ionicons/svg/duplicate.svg",
    "ear": "https://ionic.io/ionicons/svg/ear.svg",
    "earth": "https://ionic.io/ionicons/svg/earth.svg",
    "easel": "https://ionic.io/ionicons/svg/easel.svg",
    "egg": "https://ionic.io/ionicons/svg/egg.svg",
    "ellipse": "https://ionic.io/ionicons/svg/ellipse.svg",
    "ellipsis-horizontal": "https://ionic.io/ionicons/svg/ellipsis-horizontal.svg",
    "ellipsis-vertical": "https://ionic.io/ionicons/svg/ellipsis-vertical.svg",
    "enter": "https://ionic.io/ionicons/svg/enter.svg",
    "exit": "https://ionic.io/ionicons/svg/exit.svg",
    "expand": "https://ionic.io/ionicons/svg/expand.svg",
    "extension-puzzle": "https://ionic.io/ionicons/svg/extension-puzzle.svg",
    "eye": "https://ionic.io/ionicons/svg/eye.svg",
    "eye-off": "https://ionic.io/ionicons/svg/eye-off.svg",
    "eyedrop": "https://ionic.io/ionicons/svg/eyedrop.svg",
    "fast-food": "https://ionic.io/ionicons/svg/fast-food.svg",
    "female": "https://ionic.io/ionicons/svg/female.svg",
    "file-tray": "https://ionic.io/ionicons/svg/file-tray.svg",
    "file-tray-full": "https://ionic.io/ionicons/svg/file-tray-full.svg",
    "file-tray-stacked": "https://ionic.io/ionicons/svg/file-tray-stacked.svg",
    "film": "https://ionic.io/ionicons/svg/film.svg",
    "filter": "https://ionic.io/ionicons/svg/filter.svg",
    "filter-circle": "https://ionic.io/ionicons/svg/filter-circle.svg",
    "finger-print": "https://ionic.io/ionicons/svg/finger-print.svg",
    "fish": "https://ionic.io/ionicons/svg/fish.svg",
    "fitness": "https://ionic.io/ionicons/svg/fitness.svg",
    "flag": "https://ionic.io/ionicons/svg/flag.svg",
    "flame": "https://ionic.io/ionicons/svg/flame.svg",
    "flash": "https://ionic.io/ionicons/svg/flash.svg",
    "flash-off": "https://ionic.io/ionicons/svg/flash-off.svg",
    "flashlight": "https://ionic.io/ionicons/svg/flashlight.svg",
    "flask": "https://ionic.io/ionicons/svg/flask.svg",
    "flower": "https://ionic.io/ionicons/svg/flower.svg",
    "folder": "https://ionic.io/ionicons/svg/folder.svg",
    "folder-open": "https://ionic.io/ionicons/svg/folder-open.svg",
    "football": "https://ionic.io/ionicons/svg/football.svg",
    "footsteps": "https://ionic.io/ionicons/svg/footsteps.svg",
    "funnel": "https://ionic.io/ionicons/svg/funnel.svg",
    "game-controller": "https://ionic.io/ionicons/svg/game-controller.svg",
    "gift": "https://ionic.io/ionicons/svg/gift.svg",
    "git-branch": "https://ionic.io/ionicons/svg/git-branch.svg",
    "git-commit": "https://ionic.io/ionicons/svg/git-commit.svg",
    "git-compare": "https://ionic.io/ionicons/svg/git-compare.svg",
    "git-merge": "https://ionic.io/ionicons/svg/git-merge.svg",
    "git-network": "https://ionic.io/ionicons/svg/git-network.svg",
    "git-pull-request": "https://ionic.io/ionicons/svg/git-pull-request.svg",
    "glasses": "https://ionic.io/ionicons/svg/glasses.svg",
    "globe": "https://ionic.io/ionicons/svg/globe.svg",
    "golf": "https://ionic.io/ionicons/svg/golf.svg",
    "grid": "https://ionic.io/ionicons/svg/grid.svg",
    "hammer": "https://ionic.io/ionicons/svg/hammer.svg",
    "hand-left": "https://ionic.io/ionicons/svg/hand-left.svg",
    "hand-right": "https://ionic.io/ionicons/svg/hand-right.svg",
    "happy": "https://ionic.io/ionicons/svg/happy.svg",
    "hardware-chip": "https://ionic.io/ionicons/svg/hardware-chip.svg",
    "headset": "https://ionic.io/ionicons/svg/headset.svg",
    "heart": "https://ionic.io/ionicons/svg/heart.svg",
    "heart-circle": "https://ionic.io/ionicons/svg/heart-circle.svg",
    "heart-dislike": "https://ionic.io/ionicons/svg/heart-dislike.svg",
    "heart-dislike-circle": "https://ionic.io/ionicons/svg/heart-dislike-circle.svg",
    "heart-half": "https://ionic.io/ionicons/svg/heart-half.svg",
    "help": "https://ionic.io/ionicons/svg/help.svg",
    "help-buoy": "https://ionic.io/ionicons/svg/help-buoy.svg",
    "help-circle": "https://ionic.io/ionicons/svg/help-circle.svg",
    "home": "https://ionic.io/ionicons/svg/home.svg",
    "hourglass": "https://ionic.io/ionicons/svg/hourglass.svg",
    "ice-cream": "https://ionic.io/ionicons/svg/ice-cream.svg",
    "id-card": "https://ionic.io/ionicons/svg/id-card.svg",
    "image": "https://ionic.io/ionicons/svg/image.svg",
    "images": "https://ionic.io/ionicons/svg/images.svg",
    "infinite": "https://ionic.io/ionicons/svg/infinite.svg",
    "information": "https://ionic.io/ionicons/svg/information.svg",
    "information-circle": "https://ionic.io/ionicons/svg/information-circle.svg",
    "invert-mode": "https://ionic.io/ionicons/svg/invert-mode.svg",
    "journal": "https://ionic.io/ionicons/svg/journal.svg",
    "key": "https://ionic.io/ionicons/svg/key.svg",
    "keypad": "https://ionic.io/ionicons/svg/keypad.svg",
    "language": "https://ionic.io/ionicons/svg/language.svg",
    "laptop": "https://ionic.io/ionicons/svg/laptop.svg",
    "layers": "https://ionic.io/ionicons/svg/layers.svg",
    "leaf": "https://ionic.io/ionicons/svg/leaf.svg",
    "library": "https://ionic.io/ionicons/svg/library.svg",
    "link": "https://ionic.io/ionicons/svg/link.svg",
    "list": "https://ionic.io/ionicons/svg/list.svg",
    "list-circle": "https://ionic.io/ionicons/svg/list-circle.svg",
    "locate": "https://ionic.io/ionicons/svg/locate.svg",
    "location": "https://ionic.io/ionicons/svg/location.svg",
    "lock-closed": "https://ionic.io/ionicons/svg/lock-closed.svg",
    "lock-open": "https://ionic.io/ionicons/svg/lock-open.svg",
    "log-in": "https://ionic.io/ionicons/svg/log-in.svg",
    "log-out": "https://ionic.io/ionicons/svg/log-out.svg",
    "magnet": "https://ionic.io/ionicons/svg/magnet.svg",
    "mail": "https://ionic.io/ionicons/svg/mail.svg",
    "mail-open": "https://ionic.io/ionicons/svg/mail-open.svg",
    "mail-unread": "https://ionic.io/ionicons/svg/mail-unread.svg",
    "male": "https://ionic.io/ionicons/svg/male.svg",
    "male-female": "https://ionic.io/ionicons/svg/male-female.svg",
    "man": "https://ionic.io/ionicons/svg/man.svg",
    "map": "https://ionic.io/ionicons/svg/map.svg",
    "medal": "https://ionic.io/ionicons/svg/medal.svg",
    "medical": "https://ionic.io/ionicons/svg/medical.svg",
    "medkit": "https://ionic.io/ionicons/svg/medkit.svg",
    "megaphone": "https://ionic.io/ionicons/svg/megaphone.svg",
    "menu": "https://ionic.io/ionicons/svg/menu.svg",
    "mic": "https://ionic.io/ionicons/svg/mic.svg",
    "mic-circle": "https://ionic.io/ionicons/svg/mic-circle.svg",
    "mic-off": "https://ionic.io/ionicons/svg/mic-off.svg",
    "moon": "https://ionic.io/ionicons/svg/moon.svg",
    "move": "https://ionic.io/ionicons/svg/move.svg",
    "musical-note": "https://ionic.io/ionicons/svg/musical-note.svg",
    "musical-notes": "https://ionic.io/ionicons/svg/musical-notes.svg",
    "navigate": "https://ionic.io/ionicons/svg/navigate.svg",
    "navigate-circle": "https://ionic.io/ionicons/svg/navigate-circle.svg",
    "newspaper": "https://ionic.io/ionicons/svg/newspaper.svg",
    "notifications": "https://ionic.io/ionicons/svg/notifications.svg",
    "notifications-circle": "https://ionic.io/ionicons/svg/notifications-circle.svg",
    "notifications-off": "https://ionic.io/ionicons/svg/notifications-off.svg",
    "nuclear": "https://ionic.io/ionicons/svg/nuclear.svg",
    "nutrition": "https://ionic.io/ionicons/svg/nutrition.svg",
    "open": "https://ionic.io/ionicons/svg/open.svg",
    "options": "https://ionic.io/ionicons/svg/options.svg",
    "paper-plane": "https://ionic.io/ionicons/svg/paper-plane.svg",
    "partly-sunny": "https://ionic.io/ionicons/svg/partly-sunny.svg",
    "pause": "https://ionic.io/ionicons/svg/pause.svg",
    "pause-circle": "https://ionic.io/ionicons/svg/pause-circle.svg",
    "paw": "https://ionic.io/ionicons/svg/paw.svg",
    "pencil": "https://ionic.io/ionicons/svg/pencil.svg",
    "people": "https://ionic.io/ionicons/svg/people.svg",
    "people-circle": "https://ionic.io/ionicons/svg/people-circle.svg",
    "person": "https://ionic.io/ionicons/svg/person.svg",
    "person-add": "https://ionic.io/ionicons/svg/person-add.svg",
    "person-circle": "https://ionic.io/ionicons/svg/person-circle.svg",
    "person-remove": "https://ionic.io/ionicons/svg/person-remove.svg",
    "phone-landscape": "https://ionic.io/ionicons/svg/phone-landscape.svg",
    "phone-portrait": "https://ionic.io/ionicons/svg/phone-portrait.svg",
    "pie-chart": "https://ionic.io/ionicons/svg/pie-chart.svg",
    "pin": "https://ionic.io/ionicons/svg/pin.svg",
    "pint": "https://ionic.io/ionicons/svg/pint.svg",
    "pizza": "https://ionic.io/ionicons/svg/pizza.svg",
    "planet": "https://ionic.io/ionicons/svg/planet.svg",
    "play": "https://ionic.io/ionicons/svg/play.svg",
    "play-back": "https://ionic.io/ionicons/svg/play-back.svg",
    "play-back-circle": "https://ionic.io/ionicons/svg/play-back-circle.svg",
    "play-circle": "https://ionic.io/ionicons/svg/play-circle.svg",
    "play-forward": "https://ionic.io/ionicons/svg/play-forward.svg",
    "play-forward-circle": "https://ionic.io/ionicons/svg/play-forward-circle.svg",
    "play-skip-back": "https://ionic.io/ionicons/svg/play-skip-back.svg",
    "play-skip-back-circle": "https://ionic.io/ionicons/svg/play-skip-back-circle.svg",
    "play-skip-forward": "https://ionic.io/ionicons/svg/play-skip-forward.svg",
    "play-skip-forward-circle": "https://ionic.io/ionicons/svg/play-skip-forward-circle.svg",
    "podium": "https://ionic.io/ionicons/svg/podium.svg",
    "power": "https://ionic.io/ionicons/svg/power.svg",
    "pricetag": "https://ionic.io/ionicons/svg/pricetag.svg",
    "pricetags": "https://ionic.io/ionicons/svg/pricetags.svg",
    "print": "https://ionic.io/ionicons/svg/print.svg",
    "prism": "https://ionic.io/ionicons/svg/prism.svg",
    "pulse": "https://ionic.io/ionicons/svg/pulse.svg",
    "push": "https://ionic.io/ionicons/svg/push.svg",
    "qr-code": "https://ionic.io/ionicons/svg/qr-code.svg",
    "radio": "https://ionic.io/ionicons/svg/radio.svg",
    "radio-button-off": "https://ionic.io/ionicons/svg/radio-button-off.svg",
    "radio-button-on": "https://ionic.io/ionicons/svg/radio-button-on.svg",
    "rainy": "https://ionic.io/ionicons/svg/rainy.svg",
    "reader": "https://ionic.io/ionicons/svg/reader.svg",
    "receipt": "https://ionic.io/ionicons/svg/receipt.svg",
    "recording": "https://ionic.io/ionicons/svg/recording.svg",
    "refresh": "https://ionic.io/ionicons/svg/refresh.svg",
    "refresh-circle": "https://ionic.io/ionicons/svg/refresh-circle.svg",
    "reload": "https://ionic.io/ionicons/svg/reload.svg",
    "reload-circle": "https://ionic.io/ionicons/svg/reload-circle.svg",
    "remove": "https://ionic.io/ionicons/svg/remove.svg",
    "remove-circle": "https://ionic.io/ionicons/svg/remove-circle.svg",
    "reorder-four": "https://ionic.io/ionicons/svg/reorder-four.svg",
    "reorder-three": "https://ionic.io/ionicons/svg/reorder-three.svg",
    "reorder-two": "https://ionic.io/ionicons/svg/reorder-two.svg",
    "repeat": "https://ionic.io/ionicons/svg/repeat.svg",
    "resize": "https://ionic.io/ionicons/svg/resize.svg",
    "restaurant": "https://ionic.io/ionicons/svg/restaurant.svg",
    "return-down-back": "https://ionic.io/ionicons/svg/return-down-back.svg",
    "return-down-forward": "https://ionic.io/ionicons/svg/return-down-forward.svg",
    "return-up-back": "https://ionic.io/ionicons/svg/return-up-back.svg",
    "return-up-forward": "https://ionic.io/ionicons/svg/return-up-forward.svg",
    "ribbon": "https://ionic.io/ionicons/svg/ribbon.svg",
    "rocket": "https://ionic.io/ionicons/svg/rocket.svg",
    "rose": "https://ionic.io/ionicons/svg/rose.svg",
    "sad": "https://ionic.io/ionicons/svg/sad.svg",
    "save": "https://ionic.io/ionicons/svg/save.svg",
    "scale": "https://ionic.io/ionicons/svg/scale.svg",
    "scan": "https://ionic.io/ionicons/svg/scan.svg",
    "scan-circle": "https://ionic.io/ionicons/svg/scan-circle.svg",
    "school": "https://ionic.io/ionicons/svg/school.svg",
    "search": "https://ionic.io/ionicons/svg/search.svg",
    "search-circle": "https://ionic.io/ionicons/svg/search-circle.svg",
    "send": "https://ionic.io/ionicons/svg/send.svg",
    "server": "https://ionic.io/ionicons/svg/server.svg",
    "settings": "https://ionic.io/ionicons/svg/settings.svg",
    "shapes": "https://ionic.io/ionicons/svg/shapes.svg",
    "share": "https://ionic.io/ionicons/svg/share.svg",
    "share-social": "https://ionic.io/ionicons/svg/share-social.svg",
    "shield": "https://ionic.io/ionicons/svg/shield.svg",
    "shield-checkmark": "https://ionic.io/ionicons/svg/shield-checkmark.svg",
    "shield-half": "https://ionic.io/ionicons/svg/shield-half.svg",
    "shirt": "https://ionic.io/ionicons/svg/shirt.svg",
    "shuffle": "https://ionic.io/ionicons/svg/shuffle.svg",
    "skull": "https://ionic.io/ionicons/svg/skull.svg",
    "snow": "https://ionic.io/ionicons/svg/snow.svg",
    "sparkles": "https://ionic.io/ionicons/svg/sparkles.svg",
    "speedometer": "https://ionic.io/ionicons/svg/speedometer.svg",
    "square": "https://ionic.io/ionicons/svg/square.svg",
    "star": "https://ionic.io/ionicons/svg/star.svg",
    "star-half": "https://ionic.io/ionicons/svg/star-half.svg",
    "stats-chart": "https://ionic.io/ionicons/svg/stats-chart.svg",
    "stop": "https://ionic.io/ionicons/svg/stop.svg",
    "stop-circle": "https://ionic.io/ionicons/svg/stop-circle.svg",
    "stopwatch": "https://ionic.io/ionicons/svg/stopwatch.svg",
    "storefront": "https://ionic.io/ionicons/svg/storefront.svg",
    "subway": "https://ionic.io/ionicons/svg/subway.svg",
    "sunny": "https://ionic.io/ionicons/svg/sunny.svg",
    "swap-horizontal": "https://ionic.io/ionicons/svg/swap-horizontal.svg",
    "swap-vertical": "https://ionic.io/ionicons/svg/swap-vertical.svg",
    "sync": "https://ionic.io/ionicons/svg/sync.svg",
    "sync-circle": "https://ionic.io/ionicons/svg/sync-circle.svg",
    "tablet-landscape": "https://ionic.io/ionicons/svg/tablet-landscape.svg",
    "tablet-portrait": "https://ionic.io/ionicons/svg/tablet-portrait.svg",
    "telescope": "https://ionic.io/ionicons/svg/telescope.svg",
    "tennisball": "https://ionic.io/ionicons/svg/tennisball.svg",
    "terminal": "https://ionic.io/ionicons/svg/terminal.svg",
    "text": "https://ionic.io/ionicons/svg/text.svg",
    "thermometer": "https://ionic.io/ionicons/svg/thermometer.svg",
    "thumbs-down": "https://ionic.io/ionicons/svg/thumbs-down.svg",
    "thumbs-up": "https://ionic.io/ionicons/svg/thumbs-up.svg",
    "thunderstorm": "https://ionic.io/ionicons/svg/thunderstorm.svg",
    "time": "https://ionic.io/ionicons/svg/time.svg",
    "timer": "https://ionic.io/ionicons/svg/timer.svg",
    "today": "https://ionic.io/ionicons/svg/today.svg",
    "toggle": "https://ionic.io/ionicons/svg/toggle.svg",
    "trail-sign": "https://ionic.io/ionicons/svg/trail-sign.svg",
    "train": "https://ionic.io/ionicons/svg/train.svg",
    "transgender": "https://ionic.io/ionicons/svg/transgender.svg",
    "trash": "https://ionic.io/ionicons/svg/trash.svg",
    "trash-bin": "https://ionic.io/ionicons/svg/trash-bin.svg",
    "trending-down": "https://ionic.io/ionicons/svg/trending-down.svg",
    "trending-up": "https://ionic.io/ionicons/svg/trending-up.svg",
    "triangle": "https://ionic.io/ionicons/svg/triangle.svg",
    "trophy": "https://ionic.io/ionicons/svg/trophy.svg",
    "tv": "https://ionic.io/ionicons/svg/tv.svg",
    "umbrella": "https://ionic.io/ionicons/svg/umbrella.svg",
    "unlink": "https://ionic.io/ionicons/svg/unlink.svg",
    "videocam": "https://ionic.io/ionicons/svg/videocam.svg",
    "videocam-off": "https://ionic.io/ionicons/svg/videocam-off.svg",
    "volume-high": "https://ionic.io/ionicons/svg/volume-high.svg",
    "volume-low": "https://ionic.io/ionicons/svg/volume-low.svg",
    "volume-medium": "https://ionic.io/ionicons/svg/volume-medium.svg",
    "volume-mute": "https://ionic.io/ionicons/svg/volume-mute.svg",
    "volume-off": "https://ionic.io/ionicons/svg/volume-off.svg",
    "walk": "https://ionic.io/ionicons/svg/walk.svg",
    "wallet": "https://ionic.io/ionicons/svg/wallet.svg",
    "warning": "https://ionic.io/ionicons/svg/warning.svg",
    "watch": "https://ionic.io/ionicons/svg/watch.svg",
    "water": "https://ionic.io/ionicons/svg/water.svg",
    "wifi": "https://ionic.io/ionicons/svg/wifi.svg",
    "wine": "https://ionic.io/ionicons/svg/wine.svg",
    "woman": "https://ionic.io/ionicons/svg/woman.svg"
  };

  function injectIcons() {
    const elements = document.querySelectorAll('[data-canyon-icon]');
    elements.forEach(el => {
      const iconName = el.getAttribute('data-canyon-icon').trim().toLowerCase();
      const imageUrl = iconImages[iconName];
      
      if (imageUrl) {
        // Create image element
        const img = document.createElement('img');
        img.src = imageUrl;
        img.alt = iconName + ' icon';
        img.setAttribute('aria-hidden', 'true');
        
        // Clear existing content and preserve classes
        while (el.firstChild) {
          el.removeChild(el.firstChild);
        }
        
        // Preserve existing classes
        const existingClasses = el.className.split(' ').filter(c => c !== '');
        el.className = [...existingClasses, 'canyon-icon'].join(' ');
        
        // Add image
        el.appendChild(img);
      }
    });
  }

  // Immediately invoke if DOM is already loaded
  if (document.readyState !== 'loading') {
    injectIcons();
  } else {
    document.addEventListener('DOMContentLoaded', injectIcons);
  }

  // Make function available for manual invocation
  window.CanyonIcons = {
    inject: injectIcons,
    list: () => Object.keys(iconImages),
    addIcon: (name, url) => { iconImages[name] = url; }
  };
})();
